// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupermercadoAPI.Data;

#nullable disable

namespace SupermercadoAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251017192237_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SupermercadoAPI.Models.Categorias", b =>
                {
                    b.Property<int>("idCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idCategoria"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("idCategoria");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("SupermercadoAPI.Models.Inventarios", b =>
                {
                    b.Property<int>("idInventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idInventario"));

                    b.Property<int>("cantidadActual")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("idProducto")
                        .HasColumnType("int");

                    b.Property<int>("productoidProducto")
                        .HasColumnType("int");

                    b.HasKey("idInventario");

                    b.HasIndex("productoidProducto");

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("SupermercadoAPI.Models.Productos", b =>
                {
                    b.Property<int>("idProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idProducto"));

                    b.Property<int>("categoriaidCategoria")
                        .HasColumnType("int");

                    b.Property<int>("idCategoria")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("precio")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("idProducto");

                    b.HasIndex("categoriaidCategoria");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("SupermercadoAPI.Models.Usuarios", b =>
                {
                    b.Property<int>("idUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idUsuario"));

                    b.Property<string>("contrasenaHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("rol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("idUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SupermercadoAPI.Models.Inventarios", b =>
                {
                    b.HasOne("SupermercadoAPI.Models.Productos", "producto")
                        .WithMany("inventarios")
                        .HasForeignKey("productoidProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("producto");
                });

            modelBuilder.Entity("SupermercadoAPI.Models.Productos", b =>
                {
                    b.HasOne("SupermercadoAPI.Models.Categorias", "categoria")
                        .WithMany("productos")
                        .HasForeignKey("categoriaidCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categoria");
                });

            modelBuilder.Entity("SupermercadoAPI.Models.Categorias", b =>
                {
                    b.Navigation("productos");
                });

            modelBuilder.Entity("SupermercadoAPI.Models.Productos", b =>
                {
                    b.Navigation("inventarios");
                });
#pragma warning restore 612, 618
        }
    }
}
